### ISSUE TITLE
Update Python library version constant to v0.0.18

### ISSUE THREAD

**Issue by noelweichbrodt** [spokestack/spokestack-website#158]
in `gatsby-config.js`:
`PYTHON_VERSION: 'v0.0.18',`

**Comment by timmywil** [comment]
I wonder if we could automate a PR on python/android releases.

**Comment by noelweichbrodt** [comment]
josh pointed out that it isn't strictly necessary for python since version number is optional. I've hence removed the automated issue creation.

**Comment by noelweichbrodt** [comment]
i looked at auto pr creation for android, and I think it is technically possible but required more time than I was willing to commit.
