### ISSUE TITLE
many URLs in docs, etc refer to missing docs and artifacts.   nlu.tflite cannot be generated - no way to create a new account on spokestack.ai

### ISSUE THREAD

**Issue by michaelcohen-uo** [spokestack/spokestack-website#227]
### Describe the bug

Cannot build android-skeleton - nlu.tflite is not in repo and spokestack.ai is non-functional

Is this a dead project???????

### Your environment

Linux

### Expected behavior

able to build project

### Actual behavior

can't build project 

Request:
https://www.spokestack.io/account/create
Response:
ERROR
Failed to contact the origin.

Generated Thu, 25 Jan 2024 18:52:17 GMT
Request ID: J3y88MEwsL69opSuGP-wf6IFb0IWiRreYJYXMCX0sevllEfe6XeO8Q==

### Steps to reproduce

go to indicated url, https://www.spokestack.io/account/create

**Comment by timmywil** [comment]
Thanks for opening an issue. Unfortunately, Spokestack is no longer maintained. This static site is still running, but the spokestack platform is no longer under active development and the SDKs have been archived.
